### ISSUE TITLE
在下载并解压数据集后，运行data_to_png.py文件出现了问题

### ISSUE THREAD

**Issue by VOCALOID39** [BruceHan98/Chinese-Character-Recognition#1]
我已照您的要求安装了所有环境，在data创建了两个文件夹，命名如要求中所示，把数据集解压存入文件夹中，但是运行data_to_png.py出现了问题，报错：Traceback (most recent call last):
  File "E:/pythonProject1/Chinese_character_handwriting_recognition-master/train_MyModel/src/data_to_png.py", line 60, in <module>
    dir_name = '../data/test/' + '%0.5d' % char_dict[tagcode_unicode]
KeyError: '啊'
这是什么原因，急问

**Comment by VOCALOID39** [comment]
> 我已照您的要求安装了所有环境，在data创建了两个文件夹，命名如要求中所示，把数据集解压存入文件夹中，但是运行data_to_png.py出现了问题，报错：Traceback (most recent call last): File "E:/pythonProject1/Chinese_character_handwriting_recognition-master/train_MyModel/src/data_to_png.py", line 60, in dir_name = '../data/test/' + '%0.5d' % char_dict[tagcode_unicode] KeyError: '啊' 这是什么原因，急问
